**Performing matrix multiplication and finding eigen vectors and eigen values using TensorFlow**

In [1]:
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[1, 2],
			[2, 3]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right Eigen Vectors of the given square array:\n",v)


Printing the Original square array:
 [[1 2]
 [2 3]]

***************************************

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]

Printing Right Eigen Vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [2]:
# importing numpy library
import numpy as np
# create numpy 2d-array
m = np.array([[1, 2, 3],
            [2, 3, 4],
            [4, 5, 6]])
print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)
# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",v)


Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

***************************************

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01 -1.24701000e-16]

Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [3]:
#!pip install tensorflow

In [4]:
#!pip install tensorflow[and-cuda]

In [5]:
import tensorflow as tf

In [6]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[6.7160854 6.5678186]
 [4.0427275 4.684779 ]]




In [7]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-0.6149561  0.7885613]
 [ 0.7885613  0.6149561]] 

Eigen Values: 
[1.5320758 9.868789 ]



In [8]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[5.751328  3.3139641 9.2635765]
 [3.346796  7.735252  4.691977 ]
 [3.9163644 8.441784  7.1975718]]




In [9]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[ 0.09232178 -0.9182351   0.38512453]
 [ 0.6724373   0.34275144  0.6560104 ]
 [-0.7343738   0.19840813  0.64909893]] 

Eigen Values: 
[-1.0245855  3.6558332 18.052906 ]

